version: '3.8' # Docker Compose 파일 형식 버전

services:
  # 프론트엔드 서비스 정의
  frontend:
    build:
      context: .           # 현재 디렉토리에서 Dockerfile을 찾습니다.
      dockerfile: Dockerfile # 사용할 Dockerfile의 이름 (프론트엔드용)
    ports:
      - "80:80"             # 호스트의 80 포트를 컨테이너의 80 포트에 매핑
    container_name: react-app-container # docker ps에서 보일 컨테이너 이름
    restart: unless-stopped # 컨테이너가 종료되면 자동으로 재시작
    depends_on:
      - backend             # 백엔드 서비스가 먼저 시작되도록 종속성 추가 (선택 사항)

  # 백엔드 서비스 정의
  backend:
    build:
      context: .           # 현재 디렉토리에서 Dockerfile_backend를 찾습니다.
      dockerfile: Dockerfile_backend # 사용할 Dockerfile의 이름 (백엔드용)
    ports:
      - "8000:8000"         # 호스트의 8000 포트를 컨테이너의 8000 포트에 매핑
    container_name: fastapi-app # docker ps에서 보일 컨테이너 이름
    restart: unless-stopped # 컨테이너가 종료되면 자동으로 재시작
    # 만약 프론트엔드에서 백엔드 API를 호출해야 한다면, 환경 변수를 통해 주소를 전달할 수 있습니다.
    # environment:
    #   - BACKEND_URL=http://backend:8000 # Docker Compose 내부 네트워크에서는 'backend'라는 서비스 이름으로 접근

# Docker Compose가 생성할 네트워크 (기본적으로 자동으로 생성되며, 서비스들이 이 네트워크를 통해 통신)
networks:
  default: